export const signUpData = {
  firstname: '',
  lastname: '',
  email: '',
  phoneNumber: '',
  zipCode: '',
  password: '',
  confirmPassword: '',
};
export const addCarData = {
  mark: '',
  model: '',
  year: '',
  style: '',
  color: '',
  transmission: '',
  driveType: '',
  doors: '',
  cylinder: '',
  fuel: '',
  milage: '',
  vinCode: '',
  comfort: [],
  seats: [],
  safety: [],
  windows: [],
  entertainment: [],
  other: [],
  firstname: '',
  lastname: '',
  email: '',
  phoneNumber: '',
  description: '',
};
export const errorMessage = {
  empty: 'Can`t be empty',
  exist: 'This email already exist',
  firstname: '*The firstname can`t be long then 255 characters.',
  lastname: '*The firstname can`t be long then 255 characters.',
  email: 'Invalid email',
  phoneNumber: 'Invalid phone number',
  zipCode: '',
  password: '*Password must contain 6-20 character, number or symbol',
  confirmPassword: '*Enter correct password',
};

